package(default_visibility = ["//visibility:public"])

cc_library(
    name = "context",
    # srcs = ["context.cc"],
    hdrs = ["context.h"],
    deps = [
        "//galaxy/base:logging",
        "//galaxy/base:memory",
        "//galaxy/ui:sdl-window",
        # "@com_google_absl//absl/strings",
    ],
    # data = ["//textures"],
)

