cc_library(
    name = "gravitational-force",
    srcs = ["gravitational-force.cc"],
    hdrs = ["gravitational-force.h"],
)

cc_test(
    name = "gravitation-force_test",
    srcs = ["gravitational-force_test.cc"],
    deps = [
        ":gravitational-force",
        "@com_google_googletest//:gtest_main",
    ]
)

cc_library(
    name = "cumulative_distribution",
    srcs = ["cumulative_distribution.cc"],
    hdrs = ["cumulative_distribution.h"],
)