cc_library(
    name = "vec-type",
    hdrs = ["vec-type.h"],
)

cc_test(
    name = "vec-type_test",
    srcs = ["vec-type_test.cc"],
    deps = [
        ":vec-type",
        "@com_google_googletest//:gtest_main",
    ]
)